### ISSUE TITLE
Baza danych

### ISSUE THREAD

**Issue by MajNiczek** [SEllwart/TeamSpeak-CMS#1]
Cześc mógłbyś podesłać plik do bazy danych?

**Comment by SEllwart** [comment]
Niestety nie posiadam pierwotnej bazy. Należy jedynie pamiętać że wymagana jest baza mysql a nie domyślna sqlite. Mając to na uwadze można dostosować te pliki do każdej bazy. Wystarczy edytować zapytania do bazy w plikach php, zmieniając ID grup ról/województw/wieku/etc:
`$zapytanierola = "SELECT * FROM group_server_to_client WHERE id1=$id AND (group_id= '8' OR group_id= '11' OR group_id= '12' OR group_id= '14' OR group_id= '15' OR group_id= '10' OR group_id= '28' OR group_id= '29' OR group_id= '30' OR group_id= '31' OR group_id= '64' OR group_id= '65' OR group_id= '66')";`

Ten projekt działał lata temu i ostatni raz edytowałem te pliki ok 4 lat temu więc nie są one zgodne z aktualnymi standardami.

Być może któregoś dnia znajdę czas by je uaktualnić ale raczej nie nastawiałbym się na to.
